### PR TITLE
Hero page

### PR DESCRIPTION
**Pull request by ianmah**
- Fixed 404 page routing
- Changed internal links to use wouter `Link` so that the entire page doesn't reload
- Made a hero page component to prettify pages that only have text on them.
- Evened out spacing on Prizes/Sponsor/Quicklinks cards 

image
image
image

### CODE REVIEW

**Comment by ianmah** [comment]
@panjenny0 @Ciuffi i made some changes to how App.js uses `HackerApplicationProvider` could you help me check it is still working as expected

**Review by jackyzha0 — APPROVED** [review]

**Comment by Ciuffi** [comment]
The only issue I see is we'll be reloading the app more often but I don't think its a huge deal

**Comment by Ciuffi** [comment]
I need to figure out how to save the app when its HackerAppContext is unloaded but for now I think its okay to merge this.

**Review by panjenny0 — APPROVED** [review]
Looks clean!

**Pull request merged**
