### PR TITLE
use full name in review page instead of full legal name

### PR DESCRIPTION
**Pull request by acchiang**
in response to thread in #all-hands
image

### CODE REVIEW

**Review by andykwan1124 — APPROVED** [review]
wowww PR right after final

**Review by panjenny0 — APPROVED** [review]
Thank u <3

**Comment by acchiang** [comment]
> wowww PR right after final

wait @andykwan1124 how did you know HAHAHHA

**Comment by andykwan1124** [comment]
@acchiang cuz I yoinked the 310 final and came here too LOL

**Pull request merged**
