### PR TITLE
Change the title to an image (issue #32)

### PR DESCRIPTION
**Pull request by 7-baig**
- Created a new folder named 'assets' in livesite/src/
- Added provided SVG in livesite/src/assets
- Replaced text with SVG in Sidebar.js

### CODE REVIEW

**Review by ianmah — CHANGES_REQUESTED** [review]
Looks great! 🎉 
Noticed a new file `package-lock.json` was created. We use yarn in this repo instead of npm. Yarn uses `yarn.lock` instead of `package-lock.json`. Could you delete the `package-lock.json`?

**Comment by 7-baig** [comment]
Yeah sure! I can do it.

**Comment by 7-baig** [comment]
Done!

**Review by ianmah — APPROVED** [review]
awesome

**Pull request merged**
