### PR TITLE
fix missing display name crashing login

### PR DESCRIPTION
**Pull request by Ciuffi**
### firebase hates undefined values!

@anneguo3 could you test this preview and see if you can login? Unfortunately I have my last name set on github.

### CODE REVIEW

**Review by panjenny0 — APPROVED** [review]
lgtm

**Comment by anneguo3** [comment]
wait @Ciuffi I still hit an error - could it be because my entry in the db is corrupt?
Screen Shot 2020-12-04 at 12 33 58 AM

**Comment by acchiang** [comment]
@anneguo3 did you use preview or prod? if you used the preview site pls remember to clear cache and hard reload (go to dev tools, right click reload button, then choose to clear cache)

**Comment by anneguo3** [comment]
i used preview and did a reload and everything 😭

**Pull request merged**
