### PR TITLE
Part 1 of the hacker app has been hooked up

### PR DESCRIPTION
**Pull request by Ciuffi**
### I've hooked up part 1 of the application to firebase.
Check out BasicInfo.js and Part1.js for examples on how to set this up. *You don't need to do anything to enable autosave besides calling useHackerApplication*

### fixed some bugs in hacker app context
- Hacker app now properly creates new entry (instead of overwriting template)
- Ethnicity map added to hackertemplate
- hacker app loads until application is ready
- I added a new container over the navbar for part1-3 of the application so that it will save if the user logs out.

### HOW TO TEST
1. Click on the preview URL
2. Login
3. go to `/application/part-1` (since you will be redirected to `/judging`
4. Fill out some or all of the formm
5. Click logout
6. repeat 2 and 3

You should see your changes saved!

### CODE REVIEW

**Comment by Ciuffi** [comment]
@anneguo3 could you make sure you don't crash anymore (after the build finishes)

**Review by panjenny0 — DISMISSED** [review]
Tried filling out the form and it saved my data - nice!
Also tried logging out and logging back in and it pre-populated my data from before.
👍

**Comment by Ciuffi** [comment]
@panjenny0 could someone make the "next page" button and add it as well? maybe @shuting-hu

**Comment by panjenny0** [comment]
> @panjenny0 could someone make the "next page" button and add it as well? maybe @shuting-hu

Oh it's already made! i'm adding them to all the forms rightnow, gonna open a PR for it

**Comment by anneguo3** [comment]
> @anneguo3 could you make sure you don't crash anymore (after the build finishes)

she still dun work on the staging site 😞

**Comment by Ciuffi** [comment]
ok i'm removing my last name and troubleshooting @anneguo3

**Comment by shuting-hu** [comment]
> Tried filling out the form and it saved my data - nice!
> Also tried logging out and logging back in and it pre-populated my data from before.
> 👍

none of my dropdown responses are saving

**Comment by Ciuffi** [comment]
@shuting-hu they are saving but for some reason not populating properly

**Comment by shuting-hu** [comment]
> @shuting-hu they are saving but for some reason not populating properly

oohh😯😯  also the ordering of the multiselects in questions 3 change upon every refresh

**Comment by Ciuffi** [comment]
@shuting-hu I'm not sure how to fix either of these :( It looks like the dropdown component doesn't have a value field so I don't know how to set the value. Regarding the order, I don't think firebase maps are ordered so unless we add numbers not much we can do

**Comment by Ciuffi** [comment]
@anneguo3 i can't delete my last name, can you try again tho?

**Comment by panjenny0** [comment]
> > @shuting-hu they are saving but for some reason not populating properly
> 
> oohh😯😯 also the ordering of the multiselects in questions 3 change upon every refresh



> @shuting-hu I'm not sure how to fix either of these :( It looks like the dropdown component doesn't have a value field so I don't know how to set the value. Regarding the order, I don't think firebase maps are ordered so unless we add numbers not much we can do

I think the dropdowns still work without a value field. Also I think it's fine for now that the multiselects change in order upon every refresh. We can look into it when we have time after most of the major features are done 😓

**Comment by anneguo3** [comment]
> @anneguo3 i can't delete my last name, can you try again tho?

she still don't like me :( maybe worth just to look it over on screenshare over the weekend? or if u wanna add logs and i can look into it too?

**Comment by Ciuffi** [comment]
@anneguo3 please try again!

**Comment by anneguo3** [comment]
ok it seems to be a lot better of an error message - i wanted to validate by deleting myself from the db but i couldn't find an entry with my email??? so i am honestly at a loss l o l 
Screen Shot 2020-12-05 at 8 13 53 PM

**Comment by Ciuffi** [comment]
@anneguo3 It's actually an entry in firebase auth, not the database, is this the email you're using the sign up  anneguo3@gmail.com ?

**Comment by Ciuffi** [comment]
@anneguo3 also please approve if you're pleased with my explanation, just waiting on you!

**Comment by anneguo3** [comment]
> @anneguo3 It's actually an entry in firebase auth, not the database, is this the email you're using the sign up [anneguo3@gmail.com](mailto:anneguo3@gmail.com) ? (That email is already connected to your google account for nwplus-ubc-dev)

rip that's probably the case, yeet this branch in then 👀

**Review by anneguo3 — APPROVED** [review]

**Pull request merged**
